version: '3.1'
services:
  webapp:
    image: nginx:alpine
    restart: always
    ports:
      - "3009:80"
    volumes:
      - ./static:/usr/share/nginx/html
    environment:
      - FOO=BAR
      - TEST=123
      - AAA=BBB
      - BBB=AAA
